### PR TITLE
normalize person events

### PR DESCRIPTION
**Pull request by stoicflame**
I propose eliminating properties such as 'baptism', 'burial', 'birth', 'death' because those events are redundant because they can be expressed by the 'events' property.

### CODE REVIEW

**Comment by ninjudd** [comment]
These four event types are unique from other events because there can only be one per profile. Keeping them separate is a good way to enforce this constraint and is more convenient for clients reading the data.

**Comment by stoicflame** [comment]
> These four event types are unique from other events because there can only be one per profile. Keeping them separate is a good way to enforce this constraint and is more convenient for clients reading the data.

But you're not enforcing the constraint at all if you allow for these kinds of events in the person event list. What happens if there is a `death` event _and_ there is an event in the `events` property of type "death"? Which death event do clients honor as the "official" death event? How do they treat additional death events? Are they "alternate" death events? Or do all events in the `events` list get overridden by the `death` event property? What happens if there is no `death` event property, but there _is_ an event of type "death" in the event list?

So, I would disagree with you when you say that it's "more convenient" for clients reading the data. Now clients have to deal with these complexities.

**Comment by ninjudd** [comment]
These _canonical_ event types should not be put in the `events` property.

**Comment by stoicflame** [comment]
> These canonical event types should not be put in the events property.

Okay. That's easy to say, but impossible to enforce.

**Comment by ninjudd** [comment]
That's the case with every field in the schema. Adding singular fields for canonical events _in the schema_ is better than having to scan through all events and deal with duplicates, IMO.

**Comment by stoicflame** [comment]
> Adding singular fields for canonical events in the schema is better than having to scan through all events and deal with duplicates, IMO.

Fair enough. Closing the issue.

**Comment by RobertGardner** [comment]
You guys are fast! I was going to make the same arguments for keeping the canonical fields. Whew! :-)

**Pull request closed without merging**
