### PR TITLE
rename 'partner' to 'parent'

### PR DESCRIPTION
**Pull request by stoicflame**
I propose we rename 'partner' to 'parent' for consistency with the `parents` property on person and for consistency in industry.

### CODE REVIEW

**Comment by ninjudd** [comment]
I think `partners` is more clear because you can have marriages with no children. In this case, `parents` is confusing.

**Comment by stoicflame** [comment]
> I think partners is more clear because you can have marriages with no children. In this case, parents is confusing.

I was thinking that the purpose of `Family` would be to model _families_ and a marriage (with no children) would be modeled with an event.

IMO "partner" is not only using a new word to describe something that has always been "parent" in the genealogical community, but to me, "partner" just isn't clear. You can have a "partner" in a business relationship, too. And it doesn't make sense to say "Here's a family with children Fred and Mary; their partners are John and Susie." Ick.

FWIW, I'm not trying to impose some kind of gender constraint here. I'm just trying to model consistency and clarity. I don't think you'd propose renaming the `parents` property of `Person` to `partners`, so lets stay consistent. Even in a family with no children it makes sense to me to say "parents".

**Comment by stoicflame** [comment]
Hi. Just waking up this thread. So can I apply this?

**Comment by ninjudd** [comment]
I'd still prefer `partners`, but I don't feel that strongly about it. So as long as nobody thinks `parents` is confusing for families without children...

**Comment by stoicflame** [comment]
I feel bad, but I can't help feeling pretty strongly about this.

I noticed the other day an ad for an insurance agency that said "your family's partners since 1956" and I thought that if we ever needed to supply information about the insurance agent for a family, then the `partners` property would be _perfect_ for that!

But since modeling the insurance agents for a family isn't a priority at the moment, I really think we need to supply the parents of a family and drop the `partners` property.

So unless there's strong objections, I'm going to apply this change.

**Pull request merged**
