### PR TITLE
remove the deceased flag

### PR DESCRIPTION
**Pull request by stoicflame**
Remove the deceased flag (which can be inferred from the existence of a death event or death date) to reduce redundancy.

### CODE REVIEW

**Comment by ninjudd** [comment]
A separate deceased property is included because there may not be any information about the death event. In this case, adding an empty death event is cumbersome.

**Comment by stoicflame** [comment]
> A separate deceased property is included because there may not be any information about the death event. In this case, adding an empty death event is cumbersome.

You might be right. 

It's just that now you have to deal with the inconsistency questions such as "what if there's a death date, but the `deceased` property is "false"?

And why would search engines and web crawlers even need to know whether a person is dead? Users are usually searching for death date anyway.

**Comment by ninjudd** [comment]
Undead?

**Comment by stoicflame** [comment]
> Undead?

LOL!

**Comment by ninjudd** [comment]
Again this raises the question of how accurately we want the schema to represent the underlying data. If you're right that deceased is not important for search engines, then I'd be okay removing it.

**Comment by RobertGardner** [comment]
The real question isn't "do search engines need it?" but "what types of searches will people be doing?"

I don't do enough genealogical searches to answer that fully, but it seems to me that people wouldn't search for "find Robert Gardner who is dead" but would instead search for "find Robert Gardner who died around 1850".

I would recommend, though, that if we can't find a way to indicate "dead but not sure when" in the death event, then we should insert an empty record. Or find a way to modify the event to indicate the date is unknown.

**Comment by NatAtGeni** [comment]
I suppose it would be workable to create dates with simply 'unknown' for the date - this wouldn't apply only to death events, but to any event.

**Comment by ninjudd** [comment]
Couldn't we just create an empty `Event` with no `date` specified?

**Comment by stoicflame** [comment]
> I would recommend, though, that if we can't find a way to indicate "dead but not sure when" in the death event, then we should insert an empty record. Or find a way to modify the event to indicate the date is unknown.

Why? Can someone articulate the use case where this information would be useful?

**Comment by RobertGardner** [comment]
What do genealogy sites do now when the death date is unknown? Don't they put something like "Death: Unknown"? If so, then why not include that in the microdata? If it is a difficult process to provide the information, then I agree it may not be worth the effort, but some of the proposals here sound simple and natural.

What do we do with birth dates that are unknown? Shouldn't we treat them both the same?

**Comment by ninjudd** [comment]
That was the idea behind the original `deceased` field. With that in place, you can just treat `birth` and `death` the same and leave them blank for unknown data.

**Comment by stoicflame** [comment]
I'm having a hard time assessing where we landed on this. I'm okay keeping the deceased flag if we think it will help in search results. Should I close the issue or do we need more discussion?

**Comment by RobertGardner** [comment]
I commented on this thread to express my personal preferences, but I don't have a strong stance on this. I could go either way. I just think that it would be a good idea to have a means of explicitly stating the person is deceased but we don't know the date. Personally, I thought the UNKNOWN date or some variant of it (an event with no date?) was better than the deceased field. 

I also worry that if we have a deceased field and people regularly put it there with value "false" then a generic search engine that doesn't understand the schema might index "deceased" on the person, resulting in confusing search results. So if we keep the "deceased" field we should document that it should only be present if the person is actually deceased.

Just realized that we might want to suggest people not include any attributes for events that aren't known to have happened (if that's not obvious already). For example, don't include a christening event with UNKNOWN unless we know the person was christened but we just don't know the date.

**Comment by ninjudd** [comment]
Let's go with an empty `death` to indicated deceased with an unknown date and remove `deceased`.

**Pull request merged**
