### PR TITLE
Remove the 'adoptedChildren' property for clarity and normalization

### PR DESCRIPTION
**Pull request by stoicflame**
I propose we remove the `adoptedChildren` property so we don't make people have to make difficult and confusing decisions about how to separate the children of a family into separate bags.

### CODE REVIEW

**Comment by ninjudd** [comment]
I think we should keep it unless we can come up with a better way to indicate adoption.

**Comment by NatAtGeni** [comment]
Agree - we definitely need some way to indicate that a child was adopted.

**Comment by stoicflame** [comment]
> I think we should keep it unless we can come up with a better way to indicate adoption.

Can you elaborate the use case for me? Are users going to be searching for a person/family with "child" = "John" and "adoptedChild" = "Mary"? I'm just not seeing it.

**Comment by NatAtGeni** [comment]
I think the more likely use case is searching for a family where a child was adopted. For example, I know my great aunt Rowena was adopted by another family after she became an orphan - if I were able to search for families that had an `adoptedChild` named Rowena, that would certainly help to narrow the field.

**Comment by stoicflame** [comment]
> For example, I know my great aunt Rowena was adopted by another family after she became an orphan

So you're searching for a person that has an "adoption" event? That totally makes sense, but that doesn't have anything to do with the family, that's just some properties on a person.

Another option would be to get rid of the "children" property and have properties for "adoptedChildren", "stepChildren", "biologicalChildren", "fosterChildren", etc. but doesn't that seem like overkill?

**Comment by NatAtGeni** [comment]
I suppose the question is if it's better to record an adoption in relation to the family or in relation to the individual. I think either way would work, and we just have to decide which makes more sense.

We don't need to separate out other types of children. Step-children, for example, would belong to a different family that shared either the mother or the father with the current family and the step relationships (or half relationships) would be figured out that way.

Foster children seem to be an edge case that are a bit outside the scope of what we're doing. Since that's so often only a temporary situation, I'm not sure it's genealogically significant.

**Comment by ninjudd** [comment]
If we are going to store the adoption information, I think it belongs on the family, not the person. Other reasonable searches taking advantage of this would be:
- Find John and Mary Smith who adopted a child.
- Find Bob Wilson who had an adopted sibling.

**Comment by stoicflame** [comment]
I must admit, I'm a bit surprised that we disagree on this one. I'm not sure if this is necessary, but I wanted to offer an apology if I've been coming across too aggressive or flippant; I just didn't expect the push-back.

Anyway, I still disagree that this information belongs on the family.

I think @ninjudd's example searches are reasonable searches for a user to make, but I think users will much more often be searching for "just the children". I'm nervous that if we required developers to separate the children into different bags, then a search for "James the child of Mary and John" might not result in correct results, instead requiring users to search for "James the _adopted_ child of Mary and John." And @NatAtGeni's comment:

> Step-children, for example, would belong to a different family that shared either the mother or the father with the current family and the step relationships (or half relationships) would be figured out that way.

Makes me especially nervous that there would be no way to search for "James the child of Mary and John" if James were actually the _step_ child of John because the Mary/John family wouldn't list any "James" in the child list even if James always considered John his father.

But if we modeled things like "adoption" as an event on the person or "marriage" as an event on the family with a date after the birth date of a child (i.e. to model "step" relationships) then search engines will have all the information they need to accurately provide search results.

**Comment by NatAtGeni** [comment]
I know it's a little bit redundant, but this is where the relationships for `HistoricalPerson` can provide some additional data not easily available from using only `HistoricalFamily`. We've provided the ability to add immediate family members to `HistoricalPerson`, so it's possible and encouraged to list step children, adopted children, ex-spouses, ex-partners, as well as step and half brothers/sisters for a `HistoricalPerson`.

The purpose of `HistoricalFamily` is to provide the information for a union between two people and any children who may have resulted from that union. A `HistoricalPerson` can belong to multiple families - one as a child, and one or more as a partner/parent. Showing which families a `HistoricalPerson` belongs to helps to clarify the relationships.

No need for apologies!

**Comment by stoicflame** [comment]
> I know it's a little bit redundant, but this is where the relationships for HistoricalPerson can provide some additional data not easily available from using only HistoricalFamily. We've provided the ability to add immediate family members to HistoricalPerson, so it's possible and encouraged to list step children, adopted children, ex-spouses, ex-partners, as well as step and half brothers/sisters for a HistoricalPerson.

Umm.... great... so can we get rid of the `adoptedChildren` property on `HistoricalFamily`?

> No need for apologies!

Okay, good to know. Sometimes it's hard to discern nuance via e-message.

**Comment by ninjudd** [comment]
What about replacing it with an `adoptions` field on `HistoricalFamily` which is a list of `HistoricalEvent` records?

**Comment by stoicflame** [comment]
> What about replacing it with an `adoptions` field on `HistoricalFamily` which is a list of `HistoricalEvent` records?

Hey, there you go. I like that.

**Comment by stoicflame** [comment]
Hi. Just waking up this thread.

Please note the new changes that conform to the suggestion proposed by @ninjudd.

Can I apply this change?

**Comment by ninjudd** [comment]
Should we mention that the adopted child should be listed as the person on the event? Or should we add an `adoption` event to person as well?

**Comment by NatAtGeni** [comment]
I think for `HistoricalPerson` we can just use the generic events container to hold an adoption event.

**Pull request merged**
