### PR TITLE
rename baptism to christening

### PR DESCRIPTION
**Pull request by stoicflame**
since we've decided to keep around "canonical" properties for most-used events, I propose renaming `baptism` to `christening` to allow for a more generic usage of the property. I think, generally speaking, genealogists are more comfortable using `christening` to include baptism et. al. as opposed to using `baptism` to include christening et. al.

### CODE REVIEW

**Comment by ninjudd** [comment]
I would argue for removing `baptism` from the canonical events altogether if it were not such an important data field for genealogy. It is certainly possible to have multiple baptisms.

**Comment by ninjudd** [comment]
My understanding is that christening is used to mean infant baptism in this context. Is that correct? If so, then renaming `baptism` to `christening` makes sense to me.

**Comment by stoicflame** [comment]
> My understanding is that christening is used to mean infant baptism in this context. Is that correct?

Yes.

**Comment by NatAtGeni** [comment]
In the event that there are multiple baptisms, would the events other than an infant baptism be listed as 'events' for that HistoricalPerson?

**Comment by ninjudd** [comment]
Putting multiple baptisms in `events` makes sense to me. In this way, `christening` is a better name for the canonical field since you can only have one.

**Comment by stoicflame** [comment]
I think we're done with discussion on this. Can I apply the change?

I noticed that I messed up this branch by basing it off the `clarifying-document-content-description` branch. When I commit, I'll be sure to just apply 1b20e19 and not fb0b0f8.

**Comment by NatAtGeni** [comment]
Yes, this looks fine to me. Go ahead and apply it.

**Pull request closed without merging**
