### PR TITLE
move to jekyll templating engine

### PR DESCRIPTION
**Pull request by stoicflame**
Here's the work to moving to Jekyll. Note that it doesn't convert to Markdown yet--still HTML, which I think works fine for now.

I would have converted to Markdown, but I was uncertain which css styles needed to be preserved.

### CODE REVIEW

**Comment by ninjudd** [comment]
Cool!

Would you mind renaming your branch to gh-pages and removing the CNAME file so we can preview the changes at http://familysearch.github.com/historical-data.org?

**Comment by stoicflame** [comment]
Done.

I didn't want to rename the branch because I anticipate other pull requests from 'master' and don't want those pull requests to include a removal of the CNAME file. So I just created a new branch and we'll merge from master as needed.

I got a good site build message a couple of minutes ago, but the site isn't available yet. It's the first time that it's been built here, so they said it may take a minute to propogate.

https://familysearch.github.com/historical-data.org

**Comment by ninjudd** [comment]
Looks like it is available here (http://familysearch.github.com/historical-data.org), but the CSS is missing.

**Comment by stoicflame** [comment]
Woops. Forgot to add the "_layouts" directory. Take a look now.

**Comment by ninjudd** [comment]
Looks good. Thanks!

**Pull request merged**
