### PR TITLE
rename 'rev' to 'modified' to better reflect its purpose and conform to convention

### PR DESCRIPTION
**Pull request by stoicflame**
Rename 'rev' to 'modified' to better reflect its purpose and conform to established conventions.

### CODE REVIEW

**Comment by NatAtGeni** [comment]
I think this is fine. 'rev' was borrowed from microformats.

**Comment by stoicflame** [comment]
How about this one? @nunjudd? @RobertGardner?

**Comment by stoicflame** [comment]
How about this one? @ninjudd? @RobertGardner?

**Comment by ninjudd** [comment]
Fine with me. Should it be `lastModified`?

**Comment by stoicflame** [comment]
> Should it be `lastModified`?

Isn't that kinda redundant? Why would it ever be any other kind of "modified"?

**Comment by RobertGardner** [comment]
My opinion is not strong on this one, but I too prefer 'modified'.

**Comment by ninjudd** [comment]
I don't have a strong opinion either. Just wanted to consider alternatives. Another possibility is `modifiedAt` since that indicates it is a date rather than a boolean.

**Comment by RobertGardner** [comment]
For consistency with schema.org names, perhaps modifiedDate would be best.

**Comment by ninjudd** [comment]
I like consistency.

**Pull request merged**
