### PR TITLE
rename 'agent' to 'contributor' to more accurately reflect its purpose 

### PR DESCRIPTION
**Pull request by stoicflame**
Rename 'agent' to 'contributor' to more accurately reflect its purpose and conform to industry-standard terminology

### CODE REVIEW

**Comment by NatAtGeni** [comment]
Fair enough. I think contributor is probably a better descriptor than 'agent' which was borred from the hCard microformat.

**Comment by stoicflame** [comment]
So am I okay applying this one? @ninjudd and @RobertGardner haven't commented yet.

**Comment by ninjudd** [comment]
fine with me

**Comment by RobertGardner** [comment]
Sorry, for some of these I haven't felt my input was valuable. Names of fields, exactly what fields, etc., seem more like they belong to you, the domain experts. I am reading all the issues, so please assume that if I don't raise an objection, then I don't object to the change. :-)

Go ahead with this one and the others where I have not commented.

**Pull request merged**
