### PR TITLE
remove 'historical family' to reduce redundancy and complexity

### PR DESCRIPTION
**Pull request by stoicflame**
The schema definition for Historical Family is redundant; all the information can be contained in the definition for person and event. The proposal is to remove it.

### CODE REVIEW

**Comment by ninjudd** [comment]
There are cases where `HistoricalFamily` is necessary to describe relationships accurately. For example, if a father has multiple children from different wives, the only way to distinguish those children is to create separate `HistoricalFamily` records for each wife and connect them to the father through the family.

We should discuss whether this complexity is useful for the scope of historical-data.org though. It really depends on how accurately we want the microdata to reflect the underlying data.

**Comment by stoicflame** [comment]
> We should discuss whether this complexity is useful for the scope of historical-data.org though. It really depends on how accurately we want the microdata to reflect the underlying data.

Well put.

**Comment by ninjudd** [comment]
If our main goal is to get rid of duplicate data, then using `HistoricalFamily` records is actually less redundant that direct relationships between `HistoricalPerson` records. For a family of 10, using `HistoricalFamily` would result in 10 _edges_, while using direct relationships between `HistoricalPerson` records would result in 90.

That said, we currently only add microdata for relationships from the focus profile on any given page, so we don't encounter this explosion of edges in practice.

**Comment by RobertGardner** [comment]
> If our main goal is to get rid of duplicate data, then using HistoricalFamily records is actually less redundant

This was my concern when I read the proposal. Before eliminating HistoricalFamily I would like to see sample pages that demonstrate it's more compact and easier to parse/understand. Sometimes you need to denormalize to make it easier to get the information you need.

**Comment by ninjudd** [comment]
I thought some more about this. `HistoricalFamily` serves two more purposes that I can think of.
1. Store information about `marriage` and `divorce` events without storing duplicate data on both spouses.
2. Store adoption information without creating `adopted_children`, `adopted_parents` and `adopted_siblings` fields on `HistoricalPerson`.

Again though, the question is: _What searches are people going to perform?_

Do we want to enable people to search `HistoricalFamily` records for things like this?
- "Bob and Susie Smith, married in 1823"
- "Joe and Bob Smith, children of Bob and Susie"
- "John who was adopted by Mary Wilson"
- "Jason and Josh Brown, brothers through adoption"

**Comment by stoicflame** [comment]
> Do we want to enable people to search HistoricalFamily records for things like this?

Those searches seem reasonable to me. 

It's becoming clearer to me that that for this project, model flexibility takes precedence over model efficiency (i.e. elimination of redundancy). Is that an accurate statement?

**Comment by stoicflame** [comment]
Closing this issue; we'll keep `HistoricalFamily`.

**Pull request closed without merging**
